### ISSUE TITLE
Inviting other users to the app

### ISSUE THREAD

**Issue by pajatopmr** [pajato/GameChat#16]
Providing an invitation feature is a definite must do.  How to do it is the issue.  One way is to provide a share action icon in the app bar.  Another is to have an invite menu option either in the overflow menu or in the navigation drawer fixed action section.  Opinions?

**Comment by bscotty** [comment]
We also will want to provide features such as creating a new account in-client, allowing users to sign in via facebook or other methods and allowing our users to change accounts or sign out.

**Comment by pajatopmr** [comment]
This issue has been nicely resolved by Sandy.
